import {
  BarChartOutlined,
  TeamOutlined,
  BankOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  UserOutlined,
  ReadOutlined,
} from "@ant-design/icons";

export const reportjson = [
  {
    title: "Laporan Biodata Guru",
    title2: "Teacher Bidata Report Data",
    description: "Ini adalah Laporan Biodata Guru",
    photo: "",
    type: "teacher_report",
    icon: <UserOutlined />,
  },
  {
    title: "Laporan Data Nilai",
    title2: "Score Report Data",
    description: "Ini adalah Laporan Data Nilai",
    photo: "",
    type: "scores_report",
    icon: <BarChartOutlined />,
  },
  {
    title: "Laporan Data Siswa",
    title2: "Students Report Data",
    description: "Ini adalah Laporan Data Siswa",
    photo: "",
    type: "students_report",
    icon: <TeamOutlined />,
  },
  {
    title: "Laporan Data Kelas",
    title2: "Class Report Data",
    description: "Ini adalah Laporan Data Kelas",
    photo: "",
    type: "classes_report",
    icon: <BankOutlined />,
  },
  {
    title: "Laporan Data Nilai Siswa Lulus",
    title2: "Class Report Data",
    description: "Ini adalah Laporan Data Nilai siswa lulus (di atas kkm)",
    photo: "",
    type: "scores_report_pass",
    icon: <CheckCircleOutlined />,
  },
  {
    title: "Laporan Data Nilai Tidak Siswa Lulus",
    title2: "Class Report Data",
    description:
      "Ini adalah Laporan Data Nilai Tidak siswa lulus (di bawah kkm)",
    photo: "",
    type: "scores_report_fail",
    icon: <CloseCircleOutlined />,
  },
  {
    title: "Laporan Biodata Siswa",
    title2: "Students Biodata Report",
    description: "Ini adalah Laporan Biodata Siswa",
    photo: "",
    type: "student_bio_report",
    icon: <UserOutlined />,
  },
  {
    title: "Laporan Data Tugas",
    title2: "Task Report Data",
    description: "Ini adalah Laporan Data Tugas (di bawah kkm)",
    photo: "",
    type: "tasks_report",
    icon: <ReadOutlined />,
  },
];
